### PR TITLE
Fix: prefix local imports

### PR DESCRIPTION
**Pull request by eight04**
Fixes #8 

@davidqge Please review this branch.

### CODE REVIEW

**Comment by davidqge** [comment]
Sorry I didn’t know you have another branch.

Git hub contribution guide told me to fork first, and there is only master in the fork.

I tried your dev branch with option: 

{ names: {"_rollupPluginBabelHelpers": "m$babel"}, prefix: 'm$’ }

It changed to m$_rollupPluginBabelHelpers, the prefix works, 

but it did’t use the custom names. Let me know if I configured it wrong.


In the master branch, I think it’s because it need to pass full local path. I pushed my change based on the master branch in order to make above option work.

David Ge
(469) 955-9372

**Comment by eight04** [comment]
> but it did’t use the custom names.

Could you elaborate?

**Comment by davidqge** [comment]
I used these option:

{ names: {"_rollupPluginBabelHelpers": "m$babel"}, prefix: 'm$’ }

It didn’t change  _rollupPluginBabelHelpers.js  to m$babel.


David Ge
(469) 955-9372

**Comment by eight04** [comment]
It is still unclear.

> `{ names: {"_rollupPluginBabelHelpers": "m$babel"}, prefix: 'm$’ }`

Since you specify an ID `_rollupPluginBabelHelpers` instead of a file, I assume that `_rollupPluginBabelHelpers` is an external module which is imported like `import * from "_rollupPluginBabelHelpers"`.

> It didn’t change  _rollupPluginBabelHelpers.js  to m$babel.

You mentioned a file named `_rollupPluginBabelHelpers.js`. I don't know where does it come from. This plugin doesn't rename outputted files. It only modifies outputted code.

**Comment by davidqge** [comment]
Working perfect now with following config.

{ names: {"./_rollupPluginBabelHelpers.js": "m$babel"}, prefix: 'm$’ }

It’s a babel generated chunk when I specify multi entry. 

Thank you very much!

David Ge
(469) 955-9372

**Pull request merged**
